// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/AlphonsoCode/pulumi-provider-fd-provider/sdk/go/fd-provider/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetOptionalVariable(ctx *pulumi.Context) string {
	return config.Get(ctx, "fd-provider:optionalVariable")
}
func GetRequiredVariable(ctx *pulumi.Context) string {
	return config.Get(ctx, "fd-provider:requiredVariable")
}
