// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("fd-provider");

export declare const optionalVariable: string | undefined;
Object.defineProperty(exports, "optionalVariable", {
    get() {
        return __config.get("optionalVariable");
    },
    enumerable: true,
});

export declare const requiredVariable: string | undefined;
Object.defineProperty(exports, "requiredVariable", {
    get() {
        return __config.get("requiredVariable");
    },
    enumerable: true,
});

