package registry

import (
	"github.com/pulumi/pulumi-go-provider/infer"
)

type ProviderKind string

const (
	ProviderKindResource  ProviderKind = "resource"
	ProviderKindComponent ProviderKind = "component"
	ProviderKindFunction  ProviderKind = "function"
)

type ProviderRegistryEntry struct {
	PackageName       string
	Scope             string
	Kind              ProviderKind
	InferredComponent infer.InferredComponent
	InferredResource  infer.InferredResource
	InferredFunction  infer.InferredFunction
}

type providerRegistry = []ProviderRegistryEntry

// this will be auto-generated by the makefile!

var Registry providerRegistry = providerRegistry{}
